Add support for checkbox question type
avantifellows/plio-analytics pull request #25
Opened 2021-12-02 05:58 UTC by dalmia

…en watch time is same across sessions

Fixes #{issue id}

## Summary

## Test Plan

- [ ] Schema file code updates are made for both BigQuery and Postgres
- [ ] Tested locally
- [ ] Tested on staging
- [ ] Tested on production

2021-12-08 07:06 UTC, deepansh96 requested changes

2021-12-08 07:06 UTC, deepansh96 commented on schema/bigquery/SessionAnswer.js
> +      COUNT(case when question_type IN ('mcq', 'checkbox') AND answer IS NULL THEN NULL when question_type = 'subjective' AND answer IS NULL then NULL else 1 end) AS num_answered,
Why not this?
```suggestion
      COUNT(case when question_type IN ('mcq', 'checkbox', 'subjective') AND answer IS NULL THEN NULL else 1 end) AS num_answered,
```

2021-12-08 07:06 UTC, deepansh96 commented on schema/bigquery/SessionAnswer.js
> +      COUNT(case when question_type IN ('mcq', 'checkbox') AND answer IS NULL THEN NULL when question_type = 'subjective' AND answer IS NULL then NULL else 1 end) AS num_answered,
Also let's keep it consistent
SQL language strings should stay in uppercase
```suggestion
      COUNT(CASE WHEN question_type IN ('mcq', 'checkbox') AND answer IS NULL THEN NULL WHEN question_type = 'subjective' AND answer IS NULL THEN NULL ELSE 1 END) AS num_answered,
```

2021-12-08 07:06 UTC, deepansh96 commented on schema/bigquery/SessionAnswer.js
> +          when question_type IN ('mcq', 'checkbox') AND answer = question_correct_answer then 1
Here when doing `answer = question_correct_answer`, it automatically handles that the fact that the correct answer for `checkbox` type questions is an array?

2021-12-08 07:06 UTC, deepansh96 commented on schema/bigquery/SessionAnswer.js
> +          when question_type IN ('mcq', 'checkbox') AND answer = question_correct_answer then 1
Also, the same comment about staying consistent with the styles
Ideally we should do it in all the files

2021-12-08 07:06 UTC, deepansh96 commented on schema/postgres/Session.js
> +                          ORDER BY session.id DESC) AS rank
Why were we picking up the highest watch_time waala session previously?
Now it makes sense that we should pick the latest session for a user-plio combination, but I'm not sure what was the reason for picking the session with highest watch time previously?

2021-12-08 07:06 UTC, deepansh96 commented on schema/postgres/SessionAnswer.js
> +      COUNT(case when question_type IN ('mcq', 'checkbox') AND answer IS NULL THEN NULL when question_type = 'subjective' AND answer IS NULL then NULL else 1 end) AS num_answered,
Same comment as above
Why not this?
```suggestion
      COUNT(case when question_type IN ('mcq', 'checkbox', 'subjective) AND answer IS NULL else 1 end) AS num_answered,
```

2021-12-09 07:46 UTC, dalmia commented on schema/bigquery/SessionAnswer.js
> +          when question_type IN ('mcq', 'checkbox') AND answer = question_correct_answer then 1
> Here when doing answer = question_correct_answer, it automatically handles that the fact that the correct answer for checkbox type questions is an array?
yep

2021-12-15 05:17 UTC, deepansh96 approved these changes

2021-12-15 08:22 UTC, merged